GET http://localhost:3001/todos

###

POST http://localhost:3001/todos
Content-Type: application/json

{
    "text": "Lorem Ipsum 3"
}

###

DELETE http://localhost:3001/todos/648c4da0bdf05c9e3ae13d52

###

DELETE http://localhost:3001/todos

###

PUT http://localhost:3001/todos/648c4b68cd71ee7d0abdbcd9